name: Telegram Notifications

on:
  push:
    branches:
      - main
      - dashboard
      - nurse
      - student
      - backend

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d message_thread_id=${{ secrets.TELEGRAM_THREAD_ID }} \
          -d text="🚀 New Push%0A👤 User: ${{ github.actor }}%0A🌿 Branch: ${{ github.ref_name }}%0A📦 Repo: ${{ github.repository }}"